BIN = shear-test
THIS_CPPFLAGS = -I$(top_srcdir)include -DBOOST_MULTI_INDEX_ENABLE_SAFE_MODE
LIBS = -lboost_unit_test_framework

test-nonrecursive: $(BIN)
	./$<

gdb: $(BIN)
	gdb --args ./$< --catch_system_errors=no

valgrind: $(BIN)
	valgrind --suppressions=suppressions --num-callers=20 ./$< --catch_system_errors=no

